### ISSUE TITLE
"Clean" version

### ISSUE THREAD

**Issue by Adriyst** [matthen/dstc#1]
Hi,

I see a lot of references to a "clean" version of the DSTC 2 dataset - for example, in Mrksic. et al (2018), https://arxiv.org/pdf/1606.03777.pdf , see 5.1.1 for reference - but I cannot see anything related to that in this repository.  Is this "clean" version attainable still?

Thanks!

**Comment by matthen** [comment]
I don't have a copy of that- perhaps you could email directly Nikola?

**Comment by Adriyst** [comment]
I sent him a mail recently, that I have not received a response to. I do think that I found a copy of it in this repository - https://github.com/Divye02/baby-jarvis - so I am good. Thanks for getting back to me!

**Comment by matthen** [comment]
Cool- glad you found it! I'll add a reference to that data in this repo
